### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by VegarRingdalAibel** [ActionTestingX/action-toolbox#1]
We need to add option for what docker file to use
https://github.com/ActionTestingX/action-toolbox/blob/ka1/.github/workflows/tool-release-docker.yaml#L63C154-L63C172

`-f ${{ matrix.docker.docker_file }}`

If you add status steps for each step, then we could reuse same flow in docker review.
Sample of some early work I tested with
https://github.com/ActionTestingX/action-toolbox/blob/vr1/.github/workflows/tool-generate-docker.yaml

**Comment by Krande** [comment]
> We need to add option for what docker file to use
https://github.com/ActionTestingX/action-toolbox/blob/ka1/.github/workflows/tool-release-docker.yaml#L63C154-L63C172
> 
> -f ${{ matrix.docker.docker_file }}

@VegarRingdalAibel Nice catch! I added a fix for this now (I was also missing this for the release part). 

> If you add status steps for each step, then we could reuse same flow in docker review.
Sample of some early work I tested with
https://github.com/ActionTestingX/action-toolbox/blob/vr1/.github/workflows/tool-generate-docker.yaml

Yeah, I agree. It would make sense merging the core functionality into 1 workflow. Will look into this tomorrw!

**Comment by Krande** [comment]
Reusing docker has been implemented
